// CAUTION! DO NOT EDIT THIS FILE
// This is an autogenerated file. Please see conf.json at project root
#include "luping.h"

namespace lp {

struct LupingConf conf;
struct SystemConf systemConf;
struct BatteryConf batteryConf;

void initConf() {
  systemConf.test = 23;
  batteryConf.test = 15;
  conf = {systemConf, batteryConf};

  lp::modules.begin();
  lp::printf("Begin Modules");
}

}  // namespace lp
