#pragma once

// CAUTION! DO NOT EDIT THIS FILE
// This is an autogenerated file. Please see conf.json at project root

#include "battery.h"
extern BatteryModule *battery;
#include "led.h"
extern LedModule *led;

namespace lp {
void customModules();
}  // namespace lp

