#pragma once

// CAUTION! DO NOT EDIT THIS FILE
// This is an autogenerated file. Please see conf.json at project root

#include "./../luping-battery/src/battery.h"
extern BatteryModule *battery;
#include "./../luping-led/led.h"
extern LedModule *led;

namespace lp {
void customModules();
}  // namespace lp
