#include "luping-conf.h"

// CAUTION! DO NOT EDIT THIS FILE
// This is an autogenerated file. Please see conf.json at project root

namespace lp {

struct LupingConf conf;

struct BatteryConf batteryConf;
struct TestConf testConf;

void initConf() {
  conf = {batteryConf, testConf};
}

}  // namespace lp

