#pragma once

// CAUTION! DO NOT EDIT THIS FILE
// This is an autogenerated file. Please see conf.json at project root

namespace lp {

struct BatteryConf {
  float minVbat = 3000.3;
  bool test = true;
};

struct TestConf {
  char mola[5] = { "mazo" };
};


struct LupingConf {
  BatteryConf battery;
  TestConf test;
};

extern LupingConf conf;

void initConf();

}  // namespace lp

